baseURL = "https://owais.lone.pw/"
languageCode = "en-us"
title = "Owais Lone"
theme = "minos"
enableEmoji = true
paginate = 50

[params]
    Author = "Owais Lone"
    GitHubUser = "owais"
    TwitterUser = "owaislone"

[menu]
    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/blog/index.xml"
        weight = -110
